### ISSUE TITLE
User can search for locations nearby

### ISSUE THREAD

**Issue by Yang-Darren** [Yang-Darren/Final-Project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for locations nearby when entering an address

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to enter a city name and locations address and information will be displayed.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90783131/195236703-f2094b0e-1796-4f1f-8253-5288a21b82ac.png)
![image](https://user-images.githubusercontent.com/90783131/195236752-d342cbca-9fde-4fec-b3e6-2b5894699a71.png)
![image](https://user-images.githubusercontent.com/90783131/195236867-05f42226-9d67-4833-873e-df067441579c.png)
![image](https://user-images.githubusercontent.com/90783131/195236898-78205592-e299-4aa8-9adc-d502bd104b4b.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `locations.sql` to include dummy locations

### ☁️ Server Tasks

- [x] Update `server/index.js` to send a GET request to the database for locations nearby
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to enter input field
- [x] Create a component for button
- [x] Update component to display locations underneath button

### 🧑‍⚕️ Clean Up Tasks
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
