### ISSUE TITLE
User can create account

### ISSUE THREAD

**Issue by Yang-Darren** [Yang-Darren/Final-Project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can register with a username or log in to to support other features later on

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When opening the page, users can search for a location or create an account. Account will be used to support other features and record other things in the database later on. Once a user creates an account, user can sign in and informatio9n will be  stored with the user id.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90783131/205817457-15b94d6a-68ff-4434-a951-98e3d68e8f1b.png)
![image](https://user-images.githubusercontent.com/90783131/205817503-58a9998b-cb35-41cc-b718-d55865a63bca.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to with correct users information

### ☁️ Server Tasks

- [x] Update `server/index.js` to require authentication for users signing in
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to handle inputs signing in/signing up
- [x] Update component to render correct buttons depending
- [x] Update navbar component if user signs in

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
